### ISSUE TITLE
Make CatTransformer.probability_map deterministic

### ISSUE THREAD

**Issue by ManuelAlvarezC** [HDI-Project/RDT#25]
When transforming data with `CatTransformer`, the different values with their mean and standard deviation are preserved in the attribute `CatTransformer.probability_map`.

However, that process isn't fully deterministic, which make the class harder to test and debug. Until everybody uses python 3.7, where dict order is assured, we should find a way to ensure that for the same input values the same `CatTransfrmer.probability_map` is generated.

**Comment by csala** [comment]
This has already been covered in #101
