### ISSUE TITLE
Drop the usage of meta

### ISSUE THREAD

**Issue by ManuelAlvarezC** [HDI-Project/RDT#72]
RDT shouldn't load data from disk nor need a `metadata.json` file to operate. It's behavior should be the following:

- Both `HyperTransformer` and `Transformers` should have as input data which is already in the required format. That means that `HyperTransformer` shouldn't load data from disk, nor the individual transformers prepare it. 

- The filling or not of missing values should be taken out from individual transformers and be handled at the `HyperTransformer`, as specified in this [issue](https://github.com/HDI-Project/RDT/issues/57).

**Comment by csala** [comment]
The new behavior will be as follows:

## Transformers

Transformers `__init__` will expect either nothing at all (most usual case) or just the necessary arguments to know how to handle a particular column.
Transformers `fit`, `transform` and `fit_transform` will expect a single argument called `data` which will be either a series or a numpy array. If a Series is given, it will be converted into a numpy array before doing anything else. The output will be a numpy array in all cases.
Transformers `reverse_transform` will expect a single argument called `data` which will be a numpy array.

Transformers will also be agnostic to the column name within the original DataFrame.

## HyperTransformer

The `__init__` method will expect an input, called `transformers`, which will be a dictionary with column names associated to a single transformer class name and its kwargs. It will also have an optional `copy` argument, which will be boolean and default to `True`, which will indicate whether to make a copy of the input `DataFrame` before processing it or not.
The `fit`, `fit_transform`, `transform` and `reverse_transform` methods will expect a single argument, called `data`, which will be a `DataFrame` containing at least the columns indicated in the `transformers` input of the `__init__` method. The output from the `transform` and `fit_transform` method will be a `DataFrame` like the one passed as input with the columns replaced by their transformed counterparts.
